workflows:
  ios-workflow:
    name: iOS App Store Build
    max_build_duration: 120
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: codemagic

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.chenrenhan.wenxingai

      vars:
        BUNDLE_ID: "com.chenrenhan.wenxingai"
        XCODE_SCHEME: "App"

      node: 22.11.0
      xcode: latest

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true

    scripts:
      - name: Show project structure
        script: |
          set -e
          pwd
          ls -la
          echo "---- ios/App ----"
          ls -la ios/App || true

      - name: Install npm dependencies
        script: |
          npm install

      - name: Build web assets
        script: |
          npm run build

      - name: Sync Capacitor to iOS
        script: |
          npx cap sync ios

      - name: Install CocoaPods (ios/App)
        script: |
          set -e
          cd ios/App
          ls -la
          if [ ! -f "Podfile" ]; then
            echo "ERROR: Podfile not found in ios/App"
            exit 1
          fi
          pod install

      - name: Set up code signing
        script: |
          keychain initialize

      - name: Add certificates to keychain
        script: |
          keychain add-certificates

      - name: Use provisioning profiles
        script: |
          xcode-project use-profiles

      - name: Increment build number
        script: |
          set -e
          cd ios/App
          agvtool new-version -all $BUILD_NUMBER

      - name: Build ipa (workspace)
        script: |
          set -e
          cd ios/App
          if [ ! -d "App.xcworkspace" ]; then
            echo "App.xcworkspace not found. Listing:"
            ls -la
            echo "Workspaces found:"
            find . -maxdepth 2 -name "*.xcworkspace" -print || true
            exit 1
          fi

          xcode-project build-ipa \
            --workspace "App.xcworkspace" \
            --scheme "$XCODE_SCHEME"

    artifacts:
      - ios/App/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
